# Generated by Django 3.0.3 on 2020-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200318_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
