# Generated by Django 3.0.3 on 2020-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200318_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
