# Generated by Django 3.0.3 on 2020-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200318_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(related_name='_post_ingredients_+', to='blog.Post'),
        ),
    ]
