# Generated by Django 3.0.3 on 2020-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200318_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Ingredient'),
        ),
    ]
