# Generated by Django 3.0.3 on 2020-03-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200318_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_chapter1',
            new_name='text_chapter_1',
        ),
    ]
