# Generated by Django 3.0.3 on 2020-03-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200318_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_chapter2',
            new_name='text_chapter_2',
        ),
    ]
