# Generated by Django 3.0.3 on 2020-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
