# Generated by Django 3.0.3 on 2020-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_post_slider_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_slider',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
