# Generated by Django 3.0.3 on 2020-04-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_post_image_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'commentaire'},
        ),
        migrations.AlterModelOptions(
            name='mealtype',
            options={'verbose_name': 'sous-catégorie'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'recette'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'catégorie'},
        ),
    ]
